version: '3.9'

services:
  api:
    build: ./api/code
    hostname: api
    environment:
      - CONSUMER_PORT=${CONSUMER_PORT}
      - CONSUMER_ENDPOINT=${CONSUMER_ENDPOINT}
    volumes:
      - ./api/code:/app
    ports:
      - "5000:5000"
    networks:
      - network
  consumer:
    build: ./consumer/code
    hostname: consumer
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_ENDPOINT=${API_ENDPOINT}
    volumes:
      - ./consumer/code:/app
    ports:
      - "80:80"
    networks:
      - network